### ISSUE TITLE
Create a proper fork

### ISSUE THREAD

**Issue by Sciss** [etherhive/etherhive#7]
Hi there,

copy-pasting the codebase from https://github.com/tootsuite/mastodon/ is rather disingenuous. There is function made precisely for this operation, it's called a git fork. You should rebase your code, so that the forking is clearly visible, and so that it may be possible to submit patches in the future.

Copyright information notwithstanding, there is other ticket for that.

**Comment by hiveway** [comment]
Credits were added to the README to clearly state that it's a derived fork from Mastodon.

**Comment by fluffy-critter** [comment]
Even with the README updated you are still not distributing this under the terms of the AGPL license, and thus you are not in compliance.

**Comment by MightyPork** [comment]
That's not sufficient. You erased the record of hundreds of people's contributions, including mine. Delete the repository and create a proper fork including the commit history if you want to use the Mastodon codebase as a foundation for your blockchain experiment.

**Comment by dagashiya** [comment]
@MightyPork incorrect, there's no clause in AGPL that demands preservation of the commit history of a project you derive from - thus there's nothing to support your ludicrous and highly rude demand. Thanks for entertainment though - watching masadong users tremble before the might of John McAfee is very amusing.

**Comment by MightyPork** [comment]
What does this have to do with the license? What they did is very rude and if you don't see it, well i don't know what could convince you.

**Comment by dagashiya** [comment]
> What does this have to do with the license?

You put up a claim that properly crediting Mastodon as the fork's origin is "not sufficient", did you not? According to AGPL it's sufficient, making such ridiculous and baseless demands (to delete the entire repository, of all things!) is very rude and disrespectful to the devs of Hiveway project, especially since the problem was rectified already by the time of your post. Is every Mastodon user/developer like you, cherry boy?

EDIT: browser ate an "is"

**Comment by dagashiya** [comment]
Well, in the end I have no stake in this dispute so carry on. If you feel some of your rights have been impugned on, have your project leader make lawyers look into this situation - I suggest reading what should be done [on FSF's page about GPL violations](https://www.gnu.org/licenses/gpl-violation.en.html).

My take is that this is a non-issue you people keep blowing out of proportion, for whatever it matters.

**Comment by Sciss** [comment]
@dagashiya Would you mind to clarify what "you people" specifically means? I think I worded the issue clearly, and so I don't want to restate it. I am not saying anywhere that the AGPL is violated, but simply that I consider it an issue to be addressed to preserve the commit history of a forked project on a social coding platform.

**Comment by dagashiya** [comment]
@Sciss sure, I mean people getting overly worked up about it to the point of hysteria. No offence to @MightyPork but his(?) post is one example of an overreaction and fediverse (and my timeline) has been flooded with way too many toots on this topic for the past several hours.

Perhaps some of this annoyance bled through over here and in the end I probably shouldn't have taken such a tone previously.

**Comment by hiveway** [comment]
@MightyPork people can see the commits on the Mastodon project. The commit history is not erased. It's available on https://github.com/tootsuite/mastodon.

**Comment by raingloom** [comment]
So what's the reason behind deleting it from here? Why go through all this trouble instead of just pressing the fork button like a civilized person?

**Comment by fluffy-critter** [comment]
I think it’s ironic that a blockchain-focused social network would remove the commit history from their blockchain-based source control. Don’t you believe in the blockchain?

Anyway, it could be argued that the AGPL does require preservation of the commit history since that is a means of maintaining attribution to the individual contributors. You could also list the individual contributors in all the credits and so on but there’s hundreds of them.
